### ISSUE TITLE
Rename the `mongo` interface to be more specific

### ISSUE THREAD

**Issue by mmanciop** [canonical/mongodb-k8s-operator#10]
See, e.g., `mongodb-datasource` or something that expresses "I want to QUERY mongo" while leaving naming space for other relations powered by mongo, like a hypothetical "mongo-administration" if someone goes and charms Mongo OpsManager.

**Comment by balbirthomas** [comment]
The MongoDB charm has changed the name to `mongodb_datastore` (note underscore) as the relation interface name for its consumer charms. In view of this I am closing this ticket.
