### ISSUE TITLE
Ambiguous description/username

### ISSUE THREAD

**Issue by YHatahet** [canonical/mongodb-k8s-operator#236]
In this [page](https://charmhub.io/mongodb-k8s/docs/t-deploy-mongodb), the description may be a little ambiguous because it mentions to use the admin user and "admin" as the username, but in the statement below "operator" is used. Consider mentioning that the operator is the name of the admin user (if that is correct), or to update the statement above.

"""
Retrieving the username: In this case, we are using the admin user to connect to MongoDB. Use admin as the username:

`export DB_USERNAME="operator"`
"""

**Comment by MiaAltieri** [comment]
@YHatahet thank you for point this out and helping us improve our docs. This should be fixed across all docs i.e. (5/edge vs 6/edge and VM vs K8s) thanks again! :)
