### ISSUE TITLE
Reference to TLS charm + Typo

### ISSUE THREAD

**Issue by YHatahet** [canonical/mongodb-k8s-operator#237]
In the following [page](https://charmhub.io/mongodb-k8s/docs/t-enable-security), there is a link that refers to the previously used TLS charm instead of the new self-signed-certs charm even though the tutorial is using that.
Also, the TLS header has a typo : "**Transcript** Layer Security (TLS)" should become "Transport Layer Security (TLS)"

**Comment by MiaAltieri** [comment]
@YHatahet thank you for point this out and helping us improve our docs. This should be fixed across all docs i.e. (5/edge vs 6/edge and VM vs K8s) thanks again! :)
