### ISSUE TITLE
Set up a reasonable CI workflow

### ISSUE THREAD

**Issue by simskij** [canonical/mongodb-k8s-operator#28]
While there is an [embryo of a workflow here](https://github.com/canonical/mongodb-k8s-operator/blob/master/.github/workflows/python-package.yml) already, we should consider setting up a proper workflow to run on every PR as a prerequisite to merging. 

For inspiration, see [the workflow file  of the Prometheus charm](https://github.com/canonical/prometheus-k8s-operator/blob/main/.github/workflows/ci.yaml)

**Comment by delgod** [comment]
fixed in current main branch
