### ISSUE TITLE
Delete upstream-source from manifest.yaml

### ISSUE THREAD

**Issue by mmanciop** [canonical/mongodb-k8s-operator#9]
https://github.com/canonical/mongodb-operator/blob/f459eaffa9afc4eed3ec2d5b75ed8f3564c7c7aa/metadata.yaml#L31

**Comment by balbirthomas** [comment]
Closing this issue as I presume use of `upstream-source` is no longer prohibited for example as in [alertmanager-k8s-operator](https://github.com/canonical/alertmanager-k8s-operator/blob/main/metadata.yaml).
